#!/usr/bin/env bash
# Changes localhost's IP to 127.0.0.2 and facebook.com's IP to 8.8.8.8 in /etc/hosts
awk '$1 == "127.0.0.1" && $2 == "localhost" { print "127.0.0.2\tlocalhost"; next } { print }' /etc/hosts > /tmp/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> /tmp/hosts.new
cat /tmp/hosts.new > /etc/hosts
rm -f /tmp/hosts.new
